# Configurações de Build para Netlify com Next.js
[build]
  command = "npm run build"
  publish = ".next"

# Plugin essencial para Next.js no Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configurações de função para NextAuth
[functions]
  external_node_modules = ["next-auth", "@auth/supabase-adapter"]
  node_bundler = "esbuild"

# Redirecionamentos para páginas de autenticação
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Headers de segurança para autenticação
[[headers]]
  for = "/api/auth/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# Cache para assets estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configurações específicas para o ambiente de produção
[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

# Configuração de timeout para funções (importante para NextAuth)
[functions]
  timeout = 30
