# Configuração de Build
# O comando para construir o projeto e a pasta de publicação.
[build]
  command = "npm run build"
  publish = ".next"

# Plugin do Next.js para Netlify
# Este plugin cuida automaticamente de todas as configurações necessárias,
# incluindo os redirecionamentos para as rotas da API e páginas do Next.js.
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Cabeçalhos de Segurança (Opcional, mas recomendado)
# Aplica headers de segurança a todas as páginas do site.
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
